apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: demo-rate-limit
  namespace: istio-system
  labels:
    global: "false"
disable: false
plugin: rate-limiting
config:
  second: 1
  limit_by: ip
  policy: local
